# Generated by Django 2.1.7 on 2019-03-03 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0001_initial'),
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trxs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sale_time', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.Stores')),
            ],
        ),
        migrations.CreateModel(
            name='TrxsReceipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.Items')),
                ('trxs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trxs.Trxs')),
            ],
        ),
    ]
