# Generated by Django 2.1.7 on 2019-02-24 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trxs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trxs',
            old_name='store_id',
            new_name='store',
        ),
    ]
