# Generated by Django 2.1.7 on 2019-02-24 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
        ('trxs', '0002_auto_20190224_0348'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrxsReceipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.Items')),
                ('trxs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trxs.Trxs')),
            ],
        ),
    ]
