# Generated by Django 2.1.7 on 2019-03-10 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trxs', '0003_trxsreceipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trxs',
            name='sale_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
