# Generated by Django 2.1.7 on 2019-03-03 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventories',
            old_name='item_id',
            new_name='item',
        ),
    ]
