# Generated by Django 2.1.7 on 2019-03-09 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=100)),
                ('vendor_address', models.CharField(max_length=100)),
                ('vendor_city', models.CharField(max_length=100)),
                ('vendor_state', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
